<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QM.Models\QM.Models.csproj" />
    <ProjectReference Include="..\QM.Repository\QM.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next"                                   Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions"            Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions"  Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging"                     Version="10.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens"                   Version="8.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt"                  Version="8.4.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>